import { z } from 'zod';
import { validate, mongoId, isoDate } from './shared.js';

// ─── POST /patient/book-appointment ──────────────────────────────────────────
// Appointment time arrives as a display string like "09:00 AM" generated by
// the slot picker — we validate format rather than restrict to HH:MM.
const appointmentTimeSchema = z
    .string({ required_error: 'Appointment time is required' })
    .regex(
        /^(0?[1-9]|1[0-2]):[0-5]\d\s?(AM|PM)$/i,
        'Appointment time must be in format "09:00 AM"'
    );

export const bookAppointmentSchema = z.object({
    body: z.object({
        doctorId:        mongoId,
        appointmentDate: isoDate,
        appointmentTime: appointmentTimeSchema,
        type:            z.enum(['Online', 'Offline'], {
            errorMap: () => ({ message: 'Type must be Online or Offline' }),
        }),
    }),
});

// ─── POST /patient/book-package ───────────────────────────────────────────────
export const bookPackageSchema = z.object({
    body: z.object({
        packageId: mongoId,
    }),
});

export { validate };
